README.md

Hello,
A crossword puzzle with a clean web interface found on [HN](https://news.ycombinator.com/item?id=10787509).
Hope you will like it.

Add crossword puzzle

---

README.md

Hello,
Another crossword puzzle found on [HN](https://news.ycombinator.com/item?id=10787623).
Redoku is made by @padolsey.
cheers,

Add redoku

---

README.md

Added Books section

---

README.md

I haven't seen any videos on here. Videos can be a great alternative to those who don't learn well only through writing. This talk is visual and has a few exercises.

Learning link added - Talk on Regex

---

README.md

Generates regular expressions that match a set of strings.

Added regexgen

---

README.md

A good reference for _re_ python module users by Doug Hellmann

Added PyMOTW re module tutorial

---

README.md

From Intel ( see https://01.org/hyperscan ) with libpcre syntax.

Added Hyperscan

---

README.md

This tool has been invaluable to me for tools that expose regex but don't allow any comparison of the matched text.

Added a numeric range generator

---

README.md

Merge two Awesome Repos

---

README.md

Tools for translating and composing regex in English

Add Simple Regex and RegExTranslator.com

---

README.md

Add benchmarks category

---

README.md

Regex challenges with varying levels of difficulty.

Add HackerRank Regex Challenges

---

README.md

I can alphabetize the list as well if you'd like? (It's in the contribution guidelines, but doesn't seem to have been followed).

Add PHP Live Regex to Prototyping and Testing

---

README.md

Note that it is a site I maintain.

Add the page from perl-begin.org.

---

README.md

Online Regex tester for JavaScript.

Add ExtendsClass

---

README.md

RegEx to Strings is an npm package and online tool I created to generate strings that a regular expression would match.
Thanks for considering this addition to your list!

Add RegEx to Strings

---

README.md

Strings to RegEx is an npm package and online tool I created to generate a regular expression that matches a set of strings.
Thanks for considering this addition to your list!

Add Strings to RegEx

---

README.md

This adds [Super Expressive](https://github.com/francisrstokes/super-expressive) to the Libraries category.

Add Super Expressive

---

README.md

Adding my book on Python regular expressions which covers both `re` and third party `regex` modules. The book also includes 100+ exercises and reference solutions.

Add Python re(gex)?

---

.github/workflows/workflow.yml
.markdownlint.yml
README.md

Using Github's actions to run https://github.com/DavidAnson/markdownlint through https://github.com/avto-dev/markdown-lint on every push/PR. 🎉

Lint Markdown using `avto-dev/markdown-lint` action

---

README.md

This is a personal project I've been working on for a while. The GitHub repo for the project (with additional details) is [here](https://github.com/Jcparkyn/nodexr).

Add Nodexr

---

README.md

Add SafeRegex

---

README.md

Fix txt2re URL path to index page

Fix txt2re URL path
